In [17]:
pip install numpy

Requirement already satisfied: numpy in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (2.4.6)
Note: you may need to restart the kernel to use updated packages.

In [18]:
pip install pandas

Requirement already satisfied: pandas in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [19]:
pip install matplotlib

Requirement already satisfied: matplotlib in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.25 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from matplotlib) (2.4.6)
Requirement already satisfied: packaging>=20.0 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [20]:
pip install seaborn

Requirement already satisfied: seaborn in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from seaborn) (2.4.6)
Requirement already satisfied: pandas>=1.2 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from seaborn) (3.0.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from seaborn) (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=9 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/arpita/Desktop/Arpita/Netflix-Data-Analysis/.venv/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#### added lineterminator to get all new data in next row one data in 1 row

In [3]:
df = pd.read_csv('mymoviedb.csv', lineterminator= '\n')

In [4]:
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9827 entries, 0 to 9826
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9827 non-null   str
 1   Title              9827 non-null   str
 2   Overview           9827 non-null   str
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9827 non-null   int64
 5   Vote_Average       9827 non-null   float64
 6   Original_Language  9827 non-null   str
 7   Genre              9827 non-null   str
 8   Poster_Url         9827 non-null   str
dtypes: float64(2), int64(1), str(6)
memory usage: 691.1 KB

In [6]:
df['Genre'].head()

0    Action, Adventure, Science Fiction
1              Crime, Mystery, Thriller
2                              Thriller
3    Animation, Comedy, Family, Fantasy
4      Action, Adventure, Thriller, War
Name: Genre, dtype: str

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.describe()

        Popularity    Vote_Count  Vote_Average
count  9827.000000   9827.000000   9827.000000
mean     40.326088   1392.805536      6.439534
std     108.873998   2611.206907      1.129759
min      13.354000      0.000000      0.000000
25%      16.128500    146.000000      5.900000
50%      21.199000    444.000000      6.500000
75%      35.191500   1376.000000      7.100000
max    5083.954000  31077.000000     10.000000

Exploration Summary

1)we have a dataframe consisting of 9827 rows and 9 columns.
2)our dataset looks a bit tidy with no NaNs nor duplicated values.
3)Release_Data column needs to be casted into date time and to extract only the year value.
4)overview, original_language and Poster_url wouldn't be so useful during analysis, so we'll drop them
5)there is noticable outliers in Popularity column
6)Vote_Average better be categorised for proper analysis.
7)Genre columnhas comma separated values and white soaces that needs to be handled and casted into category.

In [9]:
# remove the columns

# data preprocessing
# change the release date to datetime format
df['Release_Date'] = pd.to_datetime(df['Release_Date'])
print(df['Release_Date'].dtype)

datetime64[us]

In [10]:
df['Release_Date'] = df['Release_Date'].dt.year
df['Release_Date'].dtypes

dtype('int32')

In [11]:
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

#### droping the columns

In [ ]:
df[]